{
	"Author": "baddychen",
	"ua": "",
	"homeUrl": "http://www.kuaiyunyy.com",
	"dcVipFlag": "true",
	"pCfgJs": "http://www.kuaiyunyy.com/static/js/playerconfig.js",
	"pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
	"dcShow2Vip": {},
	"dcPlayUrl": "true",
	"cateNode": "///li[@class='nav-menu-item']/a[contains(@href, 'type') and not(contains(@href,'label'))]",
	"cateName": "/@title",
	"cateId": "/@href",
	"cateIdR": "index.php/vod/type/id/(\\d+).html",
	"cateManual": {},
	"homeVodNode": "//div[@class='module-item-cover']/div[@class='module-item-pic']",
	"homeVodName": "/a/@title",
	"homeVodId": "/a/@href",
	"homeVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"homeVodImg": "/img/@data-src",
	"homeVodImgR": "",
	"homeVodMark": "following::div[contains(@class,'module-item-text')]/text()",
	"cateUrl": "http://www.kuaiyunyy.com/index.php/vod/type/id/{cateId}/page/{catePg}.html",
	"cateVodNode": "//div[@class='module-item-cover']/div[@class='module-item-pic']",
	"cateVodName": "/a/@title",
	"cateVodId": "/a/@href",
	"cateVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"cateVodImg": "/img/@data-src",
	"cateVodImgR": "",
	"cateVodMark": "following::div[contains(@class,'module-item-text')]/text()",
	"dtUrl": "http://www.kuaiyunyy.com/index.php/vod/detail/id/{vid}.html",
	"dtNode": "//main",
	"dtName": "//div[@class='video-cover']//div[@class='module-item-pic']/a/@title",
	"dtNameR": "立刻播放(.+)",
	"dtImg": "//div[@class='video-cover']//div[@class='module-item-pic']/img/@data-src",
	"dtImgR": "",
	"dtCate": "//div[@class='video-info-aux scroll-content']/div/a/text()",
	"dtCateR": "",
	"dtArea": "//div[@class='video-info-aux scroll-content']/a[last()]/text()",
	"dtAreaR": "",
	"dtYear": "//div[@class='video-info-aux scroll-content']/a[last()-1]/text()",
	"dtYearR": "",
	"dtActor": "//span[contains(@class,'video-info-itemtitle') and contains(text(), '主演')]/following-sibling::div/a/text()",
	"dtActorR": "",
	"dtDirector": "//span[contains(@class,'video-info-itemtitle') and contains(text(), '导演')]/following-sibling::div/a/text()",
	"dtDirectorR": "",
	"dtMark": "//span[contains(@class,'video-info-itemtitle') and contains(text(), '集数')]/following-sibling::*/text()",
	"dtMarkR": "",
	"dtDesc": "//span[contains(@class,'video-info-itemtitle') and contains(text(), '剧情')]/following-sibling::*/text()",
	"dtDescR": "",
	"dtFromNode": "//div[contains(@class,'module-player-tab')]/div",
	"dtFromName": "//span/text()",
	"dtFromNameR": "",
	"dtUrlNode": "//div[@class='scroll-content']",
	"dtUrlSubNode": "/a",
	"dtUrlId": "@href",
	"dtUrlIdR": "/index.php/vod/play/id/(\\S+).html",
	"dtUrlName": "/span/text()",
	"dtUrlNameR": "",
	"playUrl": "http://www.kuaiyunyy.com/index.php/vod/play/id/{playUrl}.html",
	"playUa": "",
	"searchUrl": "http://www.kuaiyunyy.com/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
	"scVodNode": "json:list",
	"scVodName": "name",
	"scVodId": "id",
	"scVodIdR": "",
	"scVodImg": "pic",
	"scVodMark": ""
}